name: Compilar APK Multipepes

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Compilar con Buildozer Action
      uses: SubspaceField/buildozer-action@v2
      with:
        buildozer_version: stable
        command: buildozer android debug

    - name: Subir el archivo APK resultante
      uses: actions/upload-artifact@v4
      with:
        name: Multipepes-APK-Instalable
        path: bin/*.apk
